version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: laranjazda
      ME_CONFIG_BASICAUTH_PASSWORD: bros2011
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: laranjazda
      ME_CONFIG_MONGODB_ADMINPASSWORD: bros2011
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "65432:65432"
    volumes:
      - /home/carlos/mongoDB
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge